# Generated by Django 5.1.3 on 2024-11-22 17:41

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=pyotp.random_base32, max_length=32),
        ),
    ]
