# Generated by Django 5.1.3 on 2024-11-25 12:59

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(default=pyotp.random_base32, editable=False, max_length=32),
        ),
    ]
