version: '3'

volumes:
  pg_data:
  minio-storage:
  static:

services:
  db:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  backend:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    build: ../frontend/
    volumes:
      - static:/frontend_static
  gateway:
    build: ./gateway/
    ports:
      - "8080:80"
    volumes:
      - static:/staticfiles
    depends_on:
      - backend
      - frontend
    restart: always