# Generated by Django 5.1.3 on 2024-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images'),
        ),
    ]
